# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "Strategy & Positioning"
pageRef = "think-tank/strategy-positioning"
weight = 10

[[main]]
name = "Society & Policy"
pageRef = "think-tank/society-policy"
weight = 20

[[main]]
name = "Culture & Story"
pageRef = "film-tv"
weight = 30

[[main]]
name = "Deep Dives"
pageRef = "film-tv/deep-dives"
parent = "Culture & Story"
weight = 10

[[main]]
name = "Industry Lens"
pageRef = "film-tv/industry-lens"
parent = "Culture & Story"
weight = 20

[[main]]
name = "Crossovers"
pageRef = "film-tv/crossovers"
parent = "Culture & Story"
weight = 30

[[main]]
name = "Frameworks"
pageRef = "frameworks"
weight = 40

[[main]]
name = "Concepts & Models"
pageRef = "frameworks/concepts-models"
parent = "Frameworks"
weight = 10

[[main]]
name = "Applications"
pageRef = "frameworks/applications"
parent = "Frameworks"
weight = 20

[[main]]
name = "Meta-Methods"
pageRef = "frameworks/meta-methods"
parent = "Frameworks"
weight = 30

[[main]]
name = "About"
pageRef = "about"
weight = 100

#[[main]]
#  name = "Parent"
#  weight = 30

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
